# This is a basic workflow to help you get started with Actions

name: AWS-TO-S3-APP2-FOLDER-UPDATE
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-vitali-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "my_app2_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

##Run automatic when push to master-------
on:
  push:
    paths:
    - 'app2_folder/**'
  
  pull_request:
    paths: 
    - 'app2_folder/**'
    #branches:
    #  - main
##----------------------------------------

##Run manual when you need for that-------
#on:
#  release:
#    types: [created]
#  
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
##----------------------------------------

jobs:
  app1-ci-part:
    runs-on: ubuntu-latest
    defaults:
      run:
        #Add this when you need go to specific folder
        working-directory: ./app2_folder

    steps:
    - name: Git clone ou repo
      uses: actions/checkout@v3

    - name: Create ZIP archive for deploy package
      run: |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        ls -la
        
    - name: Configure my AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region        : ${{ env.AWS_REGION_NAME }}
    
    - name: Copy ZIP package to S3 bucket on AWS
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Happy message CI complete
      run: echo "CI pipeline part Finished successfuly"
