# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipelines-to-AWS-EBN
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-vitali-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on:
  push:
    branches:
      - main

jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone ou repo
      uses: actions/checkout@v3

    - name: Create ZIP archive for deploy package
      run: |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        ls -la
    
    - name: Configure my AWS creds
      uses: aws-actions/configure-aws-credentials
      with:
        aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-key-id : ${{ secret.MY_AWS_SECRET_KEY }}
        aws-region        : ${{ env.AWS_REGION_NAME }}

    -name: Copy ZIP package to S3 bucket on AWS
    run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
    
    -name: Print hello message fo CI finish
    run: echo "CI pipeline part Finished successfuly"
