# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipelines-to-AWS-EBN
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-vitali-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on:
  push:
    branches:
      - main

jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone ou repo
    - uses: actions/checkout@v3

    - name: Create zip deploy package
      run: |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        ls -la
