# This is a basic workflow to help you get started with Actions

name: GitHub variables tets

# Controls when the action will run. 
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Echo github env
        run: env
      - name: Retrive short tag SHA
        run: |
          SHORT_TAG=`git rev-parse --short ${{ github.sha }}`
          echo "My short tag $SHORT_TAG"
      - name: Retrive current branch name
        run: |
          BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
          echo "My current branch $BRANCH_NAME"
