# This is a basic workflow to help you get started with Actions

name: YC Docker Keyckloak to CR

##Run automatic when push to master-------
on:
  push:
    paths:
    - 'yc_keyckloak_to_cr/**'
  
  pull_request:
    paths: 
    - 'yc_keyckloak_to_cr/**'
    #branches:
    #  - main
##----------------------------------------
# # Controls when the action will run. 
# on:
#   release:
#     types: [created]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        #Add this when you need go to specific folder
        working-directory: ./yc_keyckloak_to_cr

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crp023adrv49kq8ij7qg
          CR_REPOSITORY: keyckloak
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG