# This is a basic workflow to help you get started with Actions

name: YC-S3-UPLOAD
env:
  YC_REGION           : "ru-central1"
  YC_S3_BUCKET_NAME   : "no-terrafrom-s3-bucket"
  YC_END_POINT        : "storage.yandexcloud.net"
  YC_HOST_BUCKET      : "%(bucket)s.storage.yandexcloud.net"
  DEPLOY_PACKAGE_NAME : "my_app_${{ github.sha }}.zip"

#Run automatic when push to master-------
#on:
#  push:
#    branches:
#      - main
#----------------------------------------

#Run manual when you need for that-------
on:
  release:
    types: [created]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#----------------------------------------

jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone ou repo
      uses: actions/checkout@v3

    - name: Create ZIP archive for deploy package
      run: |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        ls -la

    # - name: Configure my AWS creds
    #   uses: aws-actions/configure-aws-credentials@v1
        
    # - name: Configure Yandex Cloud Credentials
    #   uses: yc-actions/yc-cr-login@v1
    #   with:
    #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    
    - name: Configure s3cmd for Yandex Account
      uses: s3-actions/s3cmd@v1.2.0
      with:
        #provider: aws # default is linode
        region: ${{ env.YC_REGION }}
        access_key: ${{ secrets.YC_SERVICE_ACC_ID_KEY }}
        secret_key: ${{ secrets.YC_SERVICE_ACC_SECRET_KEY }}
        provider  : aws
      
    - name: Copy ZIP package to Yandex Clous S3 bucket
      run: s3cmd --storage-class COLD --host=${{ env.YC_END_POINT }} --host-bucket=${{ env.YC_HOST_BUCKET }} put ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.YC_S3_BUCKET_NAME }}/
      
    - name: Happy message CI complete
      run: echo "CI pipeline part Finished successfuly"
